# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-01 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='geoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restname', models.CharField(max_length=40)),
                ('locations', models.CharField(max_length=40)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('bk', models.BooleanField()),
                ('sub', models.BooleanField()),
                ('tgi', models.BooleanField()),
                ('mcD', models.BooleanField()),
                ('KFC', models.BooleanField()),
            ],
        ),
    ]
